/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gazi.gorsel.programlama.proje;
import com.gazi.gorsel.programlama.proje.cnnct;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MEHMETHOYUR
 */
public class frmMuhasebe extends javax.swing.JFrame {

    /**
     * Creates new form frmMuhasebe
     */
    public frmMuhasebe() {
        initComponents();
        gelirlerogr();
         maas();
         tabloyagetir();
    }
    public void gelirlerogr(){
        cn.baglan();
        String sorgu="Select sum(ucret) as gelirler from tblogrenci ";
        ResultSet rs=cn.getir(sorgu);
        try {
            
            while (rs.next()) {
              int ucret=   rs.getInt("gelirler");
              txtogrgelir.setText(""+ucret);

            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmMuhasebe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void maas(){
        cn.baglan();
        String sorgu2="Select sum(maas) as gider1 from tblcalisan";
        ResultSet rs=cn.kurslar(sorgu2);
        try {
            while (rs.next()) {
                int maas=rs.getInt("gider1");
               txtmaas.setText(""+maas);
                System.out.println(maas);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMuhasebe.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }
    public void tabloyagetir(){
          /*int enst=Integer.parseInt(txtenstruman.getText());
  int kantingelir=Integer.parseInt(txtkantin.getText());
  int ogrgelir=Integer.parseInt(txtogrgelir.getText());
  int gelirler=enst+kantingelir+ogrgelir;
  String tarih=txttarih.getText();
  
        int maas=Integer.parseInt(txtmaas.getText());
        int mutfak=Integer.parseInt(txtmutfak.getText());
        int kira=Integer.parseInt(txtbilimum.getText());
        int fatura=Integer.parseInt(txtfatura.getText());
        int gider=mutfak+kira+fatura+maas;
        int kar=gelirler-gider;*/
        String sorgu="Select *from tblgelirgider";
       ResultSet rs=cn.getir(sorgu);
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       
        try {
            while (rs.next()) {
                int ogrucret1=rs.getInt("ogrenciucretleri");
                int kantingelir1=rs.getInt("kantingelirleri");
               int ens1=rs.getInt("enstruman");
               int eldeedilen1=rs.getInt("toplamkar");
               int maaslar1=rs.getInt("maaslar");
               int mutfakgider1=rs.getInt("mutfakgider");
               int fatura1 =rs.getInt("fatura");
               int kira1=rs.getInt("kira");
               Object[]liste={
               ogrucret1,
                   kantingelir1,
                   ens1,
                   maaslar1,
                   mutfakgider1,
                   fatura1,
                   kira1,
                   eldeedilen1
               };
               model.addRow(liste);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMuhasebe.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
            
cnnct cn=new cnnct();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtogrgelir = new javax.swing.JTextField();
        txtkantin = new javax.swing.JTextField();
        txtenstruman = new javax.swing.JTextField();
        deneme = new javax.swing.JButton();
        btngelir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmaas = new javax.swing.JTextField();
        txtmutfak = new javax.swing.JTextField();
        txtfatura = new javax.swing.JTextField();
        txtbilimum = new javax.swing.JTextField();
        btngider = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblgelir = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblgider = new javax.swing.JLabel();
        btnhesapla = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txttarih = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("Öğrencilerden Gelenler");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setText("Kantinden gelenler");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setText("Enstrüman Satışları");

        txtogrgelir.setEditable(false);

        deneme.setText("Deneme Button");
        deneme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denemeActionPerformed(evt);
            }
        });

        btngelir.setText("Gelirleri Hesapla");
        btngelir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngelirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btngelir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtogrgelir)
                            .addComponent(txtkantin)
                            .addComponent(txtenstruman, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(deneme)
                        .addGap(216, 216, 216))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtogrgelir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtkantin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtenstruman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(deneme)))
                .addGap(87, 87, 87)
                .addComponent(btngelir)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gelir", jPanel1);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setText("Maaşlar");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setText("Mutfak Giderleri");

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setText("Faturalar");

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setText("Bilimum Giderler");

        txtmaas.setEditable(false);

        btngider.setText("Giderleri Hesapla");
        btngider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbilimum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmaas, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtmutfak)
                            .addComponent(txtfatura)))
                    .addComponent(btngider))
                .addContainerGap(691, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmaas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmutfak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtfatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtbilimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btngider)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gider", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Öğrenci Ücretleri", "Kantin", "Enstrüman", "Maas", "Mutfak Giderleri", "Fatura", "Kira", "Toplam Kazanç"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Raporu Çıkar");

        jButton2.setText("Excel Tablosunda Gör");

        jLabel2.setText("Bu Ayki Gelirler");

        jLabel9.setText("Bu Ayki  Giderler");

        btnhesapla.setText("Hesaspla");
        btnhesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnhesapla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgelir, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgelir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(btnhesapla))
                    .addComponent(lblgider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Hesap Özeti", jPanel3);

        jLabel10.setText("Tarih");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttarih, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txttarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void denemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denemeActionPerformed
        
        
        
        
       
        
        
        
    }//GEN-LAST:event_denemeActionPerformed

    private void btngelirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngelirActionPerformed
        if (txttarih.getText().equals("")||txtenstruman.getText().equals("")||txtkantin.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen İlgili Alanların Hepsini Doldurunuz!!!!");
        }
        int enst=Integer.parseInt(txtenstruman.getText());
  int kantingelir=Integer.parseInt(txtkantin.getText());
  int ogrgelir=Integer.parseInt(txtogrgelir.getText());
  int gelirler=enst+kantingelir+ogrgelir;
  lblgelir.setText(""+gelirler);
        JOptionPane.showMessageDialog(rootPane, "Gider Bilgileri Hesap Özeti Kısmında Gelirleriniz Hesaplanmıştır!!");
        
        
    }//GEN-LAST:event_btngelirActionPerformed

    private void btngiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiderActionPerformed
        if (txttarih.getText().equals("")||txtmaas.getText().equals("")||txtbilimum.getText().equals("")||txtmutfak.getText().equals("")||txtfatura.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen İlgili Alanları Doldurunuz");
           txttarih.setBorder(new LineBorder(Color.RED, 2));
           txtbilimum.setBorder(new LineBorder(Color.red,2));
           txtmutfak.setBorder(new LineBorder(Color.red,2));
           txtfatura.setBorder(new LineBorder(Color.red,2));
           
        }
        int maas=Integer.parseInt(txtmaas.getText());
        int mutfak=Integer.parseInt(txtmutfak.getText());
        int bilimum=Integer.parseInt(txtbilimum.getText());
        int fatura=Integer.parseInt(txtfatura.getText());
        int gider=mutfak+bilimum+fatura+maas;
        lblgider.setText(""+gider);
        JOptionPane.showMessageDialog(rootPane, "Gelir Bilgileri Hesap Özeti Kısmında Hesaplanmıştır!!");
    }//GEN-LAST:event_btngiderActionPerformed

    private void btnhesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhesaplaActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int enst=Integer.parseInt(txtenstruman.getText());
  int kantingelir=Integer.parseInt(txtkantin.getText());
  int ogrgelir=Integer.parseInt(txtogrgelir.getText());
  int gelirler=enst+kantingelir+ogrgelir;
  String tarih=txttarih.getText();
  
        int maas=Integer.parseInt(txtmaas.getText());
        int mutfak=Integer.parseInt(txtmutfak.getText());
        int kira=Integer.parseInt(txtbilimum.getText());
        int fatura=Integer.parseInt(txtfatura.getText());
        int gider=mutfak+kira+fatura+maas;
        int kar=gelirler-gider;
        String sorgu="INSERT INTO public.tblgelirgider(\n" +
"	ogrenciucretleri, kantingelirleri, tarih, enstruman, toplamkar, maaslar, mutfakgider, fatura, kira)\n" +
"	VALUES ("+ogrgelir+","+kantingelir+", '"+tarih+"', "+enst+", "+kar+", "+maas+", "+mutfak+", "+fatura+", "+kira+");";
        
        
        
        
        cn.ekle(sorgu);
        System.out.println("Tablo Güncellendi");
        model.getDataVector().removeAllElements();
        tabloyagetir();
        
        
        
        
        
        
    }//GEN-LAST:event_btnhesaplaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMuhasebe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMuhasebe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMuhasebe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMuhasebe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMuhasebe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngelir;
    private javax.swing.JButton btngider;
    private javax.swing.JButton btnhesapla;
    private javax.swing.JButton deneme;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblgelir;
    private javax.swing.JLabel lblgider;
    private javax.swing.JTextField txtbilimum;
    private javax.swing.JTextField txtenstruman;
    private javax.swing.JTextField txtfatura;
    private javax.swing.JTextField txtkantin;
    private javax.swing.JTextField txtmaas;
    private javax.swing.JTextField txtmutfak;
    private javax.swing.JTextField txtogrgelir;
    private javax.swing.JTextField txttarih;
    // End of variables declaration//GEN-END:variables
}
