/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gazi.gorsel.programlama.proje;
import com.gazi.gorsel.programlama.proje.frmMain;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MEHMETHOYUR
 */
public class frmogretmen extends javax.swing.JFrame {
    String primary;
    String primaryname;
    String primarydate;

    /**
     * Creates new form frmPersonel
     */
    public frmogretmen() {
        initComponents();
        liste_doldur();
        ders_doldur();
       Odevler_Gelsin();
    } 
public void liste_doldur(){
    
    DefaultTableModel model=(DefaultTableModel) tblogr.getModel();
 cnnct cn=new cnnct();
 cn.baglan();
 String sorgu="Select ad,soyad,kurs from tblogrenci where kurs='"+cmbdersadi.getSelectedItem().toString()+"'";
    ResultSet rs=cn.getir(sorgu);
        try {
            while (rs.next()) {
                String ograd=rs.getString("ad");
                String ogrsoyad=rs.getString("soyad");
                String kurs=rs.getString("kurs");
                Object [] liste={ograd,ogrsoyad,kurs};
                model.addRow(liste);
                
            }   } catch (SQLException ex) {
            System.out.println(ex);
        }
        
 
}
public void ders_doldur(){
DefaultTableModel model=(DefaultTableModel) tbldersler.getModel();
cnnct cn=new cnnct();
String sorgu="Select dersadi,derssaati,derstarihi from tbldersler";
ResultSet rs=cn.getir(sorgu);
    try {
        while (rs.next()) {
            String dersad=rs.getString("dersadi");
            String dersaati=rs.getString("derssaati");
            String derstarihi=rs.getString("derstarihi");
            Object[]list={dersad,dersaati,derstarihi};
            model.addRow(list);
            
        }
    } catch (SQLException ex) {
        System.out.println(ex);
    }


}
public void Odevler_Gelsin(){
    DefaultTableModel model=(DefaultTableModel) tblodevler.getModel();
    cnnct cn=new cnnct();
    String sorgu="select * from tblodev";
    ResultSet rs=cn.getir(sorgu);
        try {
            while(rs.next()){
                String odevad=rs.getString("odevadi");
                String odev=rs.getString("odev");
                String teslim=rs.getString("teslimtarihi");
                Object[]list={odev,odevad,teslim};
                model.addRow(list);
            }   } catch (SQLException ex) {
            Logger.getLogger(frmogretmen.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cmbdersadi = new javax.swing.JComboBox<>();
        btndersekle = new javax.swing.JButton();
        cmbdersgünü = new javax.swing.JComboBox<>();
        cmbderssaati = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldersler = new javax.swing.JTable();
        btnderssil = new javax.swing.JButton();
        btndersguncelle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtodev = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbdersler2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblodevler = new javax.swing.JTable();
        btnodevekle = new javax.swing.JButton();
        btnodevgun = new javax.swing.JButton();
        txtteslim = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblogr = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbdersadi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gitar", "Bağlama", "Kanun", "Piyano", "Teori" }));
        cmbdersadi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdersadiİtemStateChanged(evt);
            }
        });
        cmbdersadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdersadiActionPerformed(evt);
            }
        });
        jPanel2.add(cmbdersadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 45, 179, -1));

        btndersekle.setText("Ekle");
        btndersekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndersekleActionPerformed(evt);
            }
        });
        jPanel2.add(btndersekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, 143, -1));

        cmbdersgünü.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma ", "Cumartesi ", "Pazar" }));
        jPanel2.add(cmbdersgünü, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 105, 179, -1));

        cmbderssaati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12.00-12.40", "12.50-13.30", "13.40-14.20", "14.30-15.10", "15.20-16.00", "16.10-16.50", "17.00-17.40", "17.50-16.30", "16.40-17.20", "17.30-18.10", "18.20-19.00", " " }));
        jPanel2.add(cmbderssaati, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 75, 179, -1));

        tbldersler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders Adı", "Saati", "Günü"
            }
        ));
        tbldersler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblderslerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldersler);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 184, -1, 363));

        btnderssil.setText("Sil");
        btnderssil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderssilActionPerformed(evt);
            }
        });
        jPanel2.add(btnderssil, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 141, 191, -1));

        btndersguncelle.setText("Güncelle");
        btndersguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndersguncelleActionPerformed(evt);
            }
        });
        jPanel2.add(btndersguncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 121, -1));

        jLabel1.setText("Ders Adı");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, -1, -1));

        jLabel2.setText("Ders Saati");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, -1, -1));

        jLabel3.setText("Ders Günü");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        jTabbedPane4.addTab("Ders Ekle", jPanel2);

        jLabel4.setText("Verilecek Ödev");

        jLabel5.setText("Teslim Tarihi");

        jLabel6.setText("Ders");

        cmbdersler2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gitar", "Bağlama", "Kanun", "Piyano", "Teori" }));
        cmbdersler2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdersadiİtemStateChanged(evt);
            }
        });

        tblodevler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders", "Verilecek Ödev", "Teslim Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblodevler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblodevlerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblodevler);

        btnodevekle.setText("Ödev VEr");
        btnodevekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnodevekleActionPerformed(evt);
            }
        });

        btnodevgun.setText("Ödevi Güncelle");
        btnodevgun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnodevgunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnodevekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnodevgun))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbdersler2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtteslim)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtodev, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbdersler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtodev, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtteslim, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnodevekle)
                    .addComponent(btnodevgun))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane4.addTab("Ödev Ekle", jPanel3);

        jPanel1.add(jTabbedPane4);

        tblogr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AD", "SOYAD", "KURS"
            }
        ));
        tblogr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblogrMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblogr);

        jPanel1.add(jScrollPane2);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
       
       
      
    }//GEN-LAST:event_formWindowActivated

    private void tblogrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblogrMouseClicked
        DefaultTableModel model=(DefaultTableModel) tblogr.getModel();
        int row=tblogr.getSelectedRow();
    }//GEN-LAST:event_tblogrMouseClicked

    private void cmbdersadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdersadiActionPerformed
        
    }//GEN-LAST:event_cmbdersadiActionPerformed

    private void btndersekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndersekleActionPerformed
       DefaultTableModel model=(DefaultTableModel)tbldersler.getModel();
       String sorgu="INSERT INTO public.tbldersler(dersadi, derssaati, derstarihi) VALUES ( '"+cmbdersadi.getSelectedItem().toString()+"','"+cmbderssaati.getSelectedItem().toString()+"' , '"+cmbdersgünü.getSelectedItem().toString()+"')";
       cnnct cn=new cnnct();
       cn.baglan();
       cn.ekle(sorgu);
       model.getDataVector().removeAllElements();
       ders_doldur();
    }//GEN-LAST:event_btndersekleActionPerformed

    private void btnderssilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderssilActionPerformed
        
        try {
            DefaultTableModel model=(DefaultTableModel)tbldersler.getModel();
        String sorgu="DELETE FROM tbldersler WHERE dersadi='"+cmbdersadi.getSelectedItem().toString()+"'AND dersadi='"+primaryname+"'AND derstarihi='"+primarydate+"'";
        cnnct cn=new cnnct();
        cn.sil(sorgu);
        cn.baglan();
        model.getDataVector().removeAllElements();
        ders_doldur();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        primaryname="";
        primarydate="";
        
    }//GEN-LAST:event_btnderssilActionPerformed

    private void tblderslerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblderslerMouseClicked
       DefaultTableModel model=(DefaultTableModel)tbldersler.getModel();
       int row=tbldersler.getSelectedRow();
       cmbdersadi.setSelectedItem(model.getValueAt(row, 0).toString());
       cmbdersgünü.setSelectedItem(model.getValueAt(row, 2).toString());
       cmbderssaati.setSelectedItem(model.getValueAt(row, 1).toString());
       primaryname=model.getValueAt(row, 0).toString();
       primarydate=model.getValueAt(row, 2).toString();
       
    }//GEN-LAST:event_tblderslerMouseClicked

    private void cmbdersadiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdersadiİtemStateChanged
           DefaultTableModel model=(DefaultTableModel) tblogr.getModel();
            model.getDataVector().removeAllElements();
 cnnct cn=new cnnct();
 cn.baglan();

 if (cmbdersadi.getSelectedItem().toString().equals("Teori")||cmbdersler2.getSelectedItem().toString().equals("Teori")) {
            String sorgu="Select ad,soyad,kurs from tblogrenci ";
            ResultSet rs=cn.getir(sorgu);
        try {
            while (rs.next()) {
                String ograd=rs.getString("ad");
                String ogrsoyad=rs.getString("soyad");
                String kurs=rs.getString("kurs");
                Object [] liste={ograd,ogrsoyad,kurs};
                model.addRow(liste);
                
            }   } catch (SQLException ex) {
            System.out.println(ex);
        }
        }
 else{
 String sorgu="Select ad,soyad,kurs from tblogrenci where kurs='"+cmbdersadi.getSelectedItem().toString()+"'";
 String sorgu2="Select ad,soyad,kurs from tblogrenci where kurs='"+cmbdersler2.getSelectedItem().toString()+"'";
 ResultSet rs=cn.getir(sorgu);
 ResultSet rs2=cn.girisyetkisi(sorgu2);
        try {
            while (rs.next()) {
                String ograd=rs.getString("ad");
                String ogrsoyad=rs.getString("soyad");
                String kurs=rs.getString("kurs");
                Object [] liste={ograd,ogrsoyad,kurs};
                model.addRow(liste);
                
            }   } catch (SQLException ex) {
            System.out.println(ex);
        }
        
               try {
                   while(rs2.next()){
                String ograd1=rs2.getString("ad");
                String ogrsoyad1=rs2.getString("soyad");
                String kurs1=rs2.getString("kurs");
                Object [] liste={ograd1,ogrsoyad1,kurs1};
                model.addRow(liste);
                
                   }
               } catch (SQLException ex) {
                   Logger.getLogger(frmogretmen.class.getName()).log(Level.SEVERE, null, ex);
               }
              
 }
 
    
        
        
    }//GEN-LAST:event_cmbdersadiİtemStateChanged

    private void btnodevekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnodevekleActionPerformed
        DefaultTableModel model=(DefaultTableModel) tblodevler.getModel();
        
        String sorgu="INSERT INTO public.tblodev(odevadi, odev, teslimtarihi) VALUES ('"+txtodev.getText()+"', '"+cmbdersler2.getSelectedItem().toString()+"', '"+txtteslim.getText()+"');";
        cnnct cn=new cnnct();
        cn.ekle(sorgu);
        model.getDataVector().removeAllElements();
        Odevler_Gelsin();
    }//GEN-LAST:event_btnodevekleActionPerformed

    private void tblodevlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblodevlerMouseClicked
       DefaultTableModel model=(DefaultTableModel) tblodevler.getModel();
       int row=tblodevler.getSelectedRow();
       cmbdersler2.setSelectedItem(model.getValueAt(row, 0).toString());
       txtodev.setText(model.getValueAt(row, 1).toString());
       txtteslim.setText(model.getValueAt(row, 2).toString());
       primary=model.getValueAt(row, 1).toString();
       
    }//GEN-LAST:event_tblodevlerMouseClicked

    private void btnodevgunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnodevgunActionPerformed
        try {
            DefaultTableModel model=(DefaultTableModel)tblodevler.getModel();
    
       String sorgu="UPDATE public.tblodev SET odevadi='"+txtodev.getText()+"', odev='"+cmbdersler2.getSelectedItem().toString()+"', teslimtarihi='"+txtteslim.getText()+"' WHERE odevadi='"+primary+"' AND teslimtarihi='"+txtteslim.getText()+"';";
       cnnct cn=new cnnct();
       cn.guncelle(sorgu);
       model.getDataVector().removeAllElements();
       Odevler_Gelsin();
        System.out.println(primary);
        } catch (Exception e) {
            System.out.println(e);
        }
primary="";
    }//GEN-LAST:event_btnodevgunActionPerformed

    private void btndersguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndersguncelleActionPerformed
       
        try {
            DefaultTableModel model=(DefaultTableModel)tbldersler.getModel();
        String sorgu="UPDATE public.tbldersler SET  dersadi='"+cmbdersadi.getSelectedItem().toString()+"', derssaati='"+cmbderssaati.getSelectedItem().toString()+"', derstarihi='"+cmbdersgünü.getSelectedItem().toString()+"' WHERE dersadi='"+primaryname+"' AND derstarihi='"+primarydate+"' ";
        cnnct cn=new cnnct();
        cn.guncelle(sorgu);
        model.getDataVector().removeAllElements();
        ders_doldur();
        } catch (Exception e) {
            System.out.println(e);
        }

        primaryname="";
        primarydate="";
        
        
    }//GEN-LAST:event_btndersguncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmogretmen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndersekle;
    private javax.swing.JButton btndersguncelle;
    private javax.swing.JButton btnderssil;
    private javax.swing.JButton btnodevekle;
    private javax.swing.JButton btnodevgun;
    private javax.swing.JComboBox<String> cmbdersadi;
    private javax.swing.JComboBox<String> cmbdersgünü;
    private javax.swing.JComboBox<String> cmbdersler2;
    private javax.swing.JComboBox<String> cmbderssaati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tbldersler;
    private javax.swing.JTable tblodevler;
    private javax.swing.JTable tblogr;
    private javax.swing.JTextField txtodev;
    private javax.swing.JTextField txtteslim;
    // End of variables declaration//GEN-END:variables
}
